### ISSUE TITLE
resnet3d inconsistency with ANTsRNet

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsPyNet#37]
2d appears to be ok at least with default settings.

in 3d, ANTsRNet:

```
createResNetModel3D(list(128, 128, 128, 1))
```
gives `Total params: 159,536,104`

whereas 

```
antspynet.create_resnet_model_3d(( 128, 128, 128, 1)).summary()
```

gives `Total params: 174,141,416`

my use case was getting a python equivalent to:

```
rnmdl =  createResNetModel3D( list(NULL,NULL,NULL,4),
  numberOfClassificationLabels = 1,
  layers = 1:3,
  residualBlockSchedule = c(3,4,6,3), squeezeAndExcite = TRUE,
  lowestResolution = 32, cardinality = 1, mode = "regression" )
```

which had the same issue ( more params in py ).

**Comment by ntustison** [comment]
Let me take a look.

**Comment by ntustison** [comment]
Okay, I think it's fixed.

**Comment by stnava** [comment]
I believe that fixed the default case but this now has a different problem --- *fewer* parameters in python

```
import antspynet
antspynet.create_resnet_model_3d( (None,None,None,4),
  number_of_classification_labels = 1,
  layers = (1,2,3),
  residual_block_schedule = (3,4,6,3), squeeze_and_excite = True,
  lowest_resolution = 32, cardinality = 1, mode = "regression" ).summary()
```

`Total params: 14,775,969`

vs

```
library(ANTsRNet)  
createResNetModel3D( list(NULL,NULL,NULL,4),
    numberOfClassificationLabels = 1,
    layers = 1:3,
    residualBlockSchedule = c(3,4,6,3), squeezeAndExcite = TRUE,
    lowestResolution = 32, cardinality = 1, mode = "regression" )
```

`Total params: 15,011,489`

**Comment by ntustison** [comment]
Oops.  Heading out the door but I'll look at this when I get back.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTsPyNet/commit/b9316b165862314c6f7a8e3d3482bbccfa5ebe5f

Okay, I think it's fixed.  I hadn't enabled the "squeeze and excite" option in one of the internal functions (which was false by default).  This had to be fixed in both 2-D and 3-D.  The number of parameters is now the same for your test case above.  Note that I also made some cosmetic changes in both ANTsPyNet and ANTsRNet.  Most of them had to do with removing obsolete code associated with a theano backend.  But the ANTsRNet model should not have changed with the cosmetic changes.
