### ISSUE TITLE
U-net optimization for mouse MRI data

### ISSUE THREAD

**Issue by tfrawleyNIA** [ANTsX/ANTsPyNet#67]
Hi everyone,

Thank you for your work and creating a useful tool!

I am using the U-net model from ANTsPyNet to segment the abdominal wall cavity in mouse MRI data. I am currently getting a loss of 0.99704 during training (200 epochs, 64 steps, 32 batchsize, 1e-04 lr) and dice scores between .95 and .97 for unseen mice. I'm trying to optimize training to get more accuracy with unseen data and I have a question about preprocessing. I am currently using a non-local mean filter to smooth the image, however I'm curious if there would be a benefit to cropping the image and/or removing noise left over from the MRI machine?

I could remove ~10-20 pixels around the edges of the MRI scan to limit the field of view as much as possible to just the section of the mouse.

I also can take an average from a section of background pixels to get a measurement of noise and subtract that from the whole image. (I understand these values might come from the MRI machine itself when it reconstructs the image based on some machine settings)

Please let me know if these steps sound useful for getting the best quality data for training. The MRI data is coming from a Bruker machine. Thanks for your time.

**Comment by ntustison** [comment]
Although we've done some stuff with mice data, the specificity of your questions is beyond our experience.  Your best bet is just to experiment yourself to answer these questions.

**Comment by ntustison** [comment]
However, I might add that these modifications are relatively minor and you're already getting good results so I'm guessing they won't make much difference.

**Comment by tfrawleyNIA** [comment]
Thank you. Do you know what dice scores you all have been able to get on unseen data so I might have a better sense of what accuracy is realistic when trying to optimize?

**Comment by ntustison** [comment]
Measures, such as Dice, are simply quantitative surrogates for what one really wants which is a "good" segmentation.  However, defining "good" depends on context and is one of the areas of difficulty in this type of research.  I mentioned above that our experience in this area is minimal so we wouldn't be able to tell you, with confidence, if 0.97 Dice on unseen data for your problem is good enough.  That's something for you to decide by actually looking at the results (perhaps with your clinical collaborators) and their downstream effects in your analysis.  If it's not good enough, considering that your optimizing your performance metric close to its maximal value, Dice might not adequately capture what you're trying to obtain and you might need to reconfigure your optimization strategy.

**Comment by tfrawleyNIA** [comment]
Thanks!
