### ISSUE TITLE
cpu allocator exceeds 10% of free memory.  

### ISSUE THREAD

**Issue by dvictorious1** [ANTsX/ANTsPyNet#85]
Trying to run AntsPy script on Linux server with 128 GB RAM and get message from tensor flow cpu_allocator that that allocation exceeds 10% of memory.   

<img width="928" alt="Screenshot 2023-08-07 at 2 51 58 PM" src="https://github.com/ANTsX/ANTsPy/assets/70602122/60314c37-d906-4931-b955-e84402e42610">

I am wondering if this task could better be accomplished using a Antspy Singularity on our Grid.  Nick suggested I contact Phil Cook to see if he has contructed one.

**Comment by cookpa** [comment]
I have containers on Dockerhub that you can use to build a singularity image, but I'm not sure that will reduce memory usage.

First thing would be to check we're not using too many threads.

You would control basic ANTs operations with ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=N and tensorflow operations with

tf.config.threading.set_inter_op_parallelism_threads(N)
tf.config.threading.set_intra_op_parallelism_threads(N)

I'd set threads to 1 and see if you can use less memory. 

You might also want to check available resources with `free`, because the individual allocations complained about in your screen shot appear to be way less than 10% of 128 Gb

**Comment by cookpa** [comment]
Here are the docker containers

https://hub.docker.com/repository/docker/cookpa/antspynet/tags?page=1&ordering=last_updated

You can build a singularity image with

`singularity build antspynet-latest.sif docker://cookpa/antspynet:latest`

**Comment by dvictorious1** [comment]
My thought was to build a singularity and attempt to run this on our multi-compute node grid.   I will be calling the batch with SLURM.  Will tf.config.threading allow me to utilize threads according to multiple CPUs specifide in sbatch?

**Comment by cookpa** [comment]
I've not used SLURM, so this might not be the right variable to use, but something like this in your job script might do it:

```
import os

num_cpu = int(os.environ.get('SLURM_CPUS_PER_TASK') or 1)

# set this before importing ants, if not already set on command line
# os.environ['ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS'] = str(num_cpu)

import ants
import tensorflow as tf

tf.config.threading.set_inter_op_parallelism_threads(num_cpu)
tf.config.threading.set_intra_op_parallelism_threads(num_cpu)
  
```

Or you might just the tensorflow CPUs to 1 if you're concerned about memory use. The tensorflow part brain extraction is fairly fast. You can separately do the conventional preprocessing with multiple threads by setting the ITK variable.

If it's of any use, here's a simple script that I wrote to do brain extraction from the command line on my cluster. 

https://github.com/ftdc-picsl/pmacsANTsPyNet/blob/main/scripts/antsxnet_brain_extraction.py

I do

```
tf.keras.backend.clear_session()
tf.config.threading.set_intra_op_parallelism_threads(threads)
tf.config.threading.set_inter_op_parallelism_threads(threads)
```

I'm not sure what the keras thing does, I copied this from an example that @ntustison gave me
