### ISSUE TITLE
Complicated Dockerfile

### ISSUE THREAD

**Issue by mateuszpawlik** [ANTsX/ANTsPyNet#89]
I was wandering if there is any reason behind the complexity of your [recommended Dockerfile](https://github.com/cookpa/ANTsXContainers/blob/master/docker/ANTsPyNet/Dockerfile). On a side, it would be great if there is a link to the Docker resources in the README.

I had many problems with using your Dockerfile because of the users and file permissions inside of Docker and those of the mounted directories.

This simple Dockerfile works for me much better:
```dockerfile
FROM python:3.11-slim
  
RUN python -m pip install --upgrade pip
RUN pip install antspynet==0.2.3
```
I had to use Python 3.11 because pip couldn't find the right tensorflow versions for the newest one.

**Comment by cookpa** [comment]
Yes, if you bind the antsxnet-cache directory to a mounted directory, it should solve the data problem. You just have to be careful to maintain that - it breaks containerization a bit because your results will depend on both the container version and the state of that directory.

In singularity the user does get ignored, so it's necessary to run

```
singularity --cleanenv --no-home  --home /home/antspyuser
```

This doesn't change $USER but it makes the container see $HOME as /home/antspyuser.

**Comment by mateuszpawlik** [comment]
Thanks. We can close this issue, if nothing is to be done.
